export const movieCollectionMock = [
  {
    slug: "originals",
    title: "Netflix Originals",
    items: {
      page: 1,
      results: [
        {
          adult: false,
          backdrop_path: "/22z44LPkMyf5nyyXvv8qQLsbom.jpg",
          genre_ids: [27, 9648, 53],
          id: 631842,
          original_language: "en",
          original_title: "Knock at the Cabin",
          overview:
            "While vacationing at a remote cabin, a young girl and her two fathers are taken hostage by four armed strangers who demand that the family make an unthinkable choice to avert the apocalypse. With limited access to the outside world, the family must decide what they believe before all is lost.",
          popularity: 3975.228,
          poster_path: "/dm06L9pxDOL9jNSK4Cb6y139rrG.jpg",
          release_date: "2023-02-01",
          title: "Knock at the Cabin",
          video: false,
          vote_average: 6.6,
          vote_count: 826,
        },
        {
          adult: false,
          backdrop_path: "/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg",
          genre_ids: [28, 12, 878],
          id: 505642,
          original_language: "en",
          original_title: "Black Panther: Wakanda Forever",
          overview:
            "Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death.  As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.",
          popularity: 3095.305,
          poster_path: "/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
          release_date: "2022-11-09",
          title: "Black Panther: Wakanda Forever",
          video: false,
          vote_average: 7.4,
          vote_count: 3868,
        },
        {
          backdrop_path: "/fTLMsF3IVLMcpNqIqJRweGvVwtX.jpg",
          genre_ids: [28, 80, 53],
          id: 1035806,
          original_language: "en",
          original_title: "Detective Knight: Independence",
          overview:
            "Detective James Knight 's last-minute assignment to the Independence Day shift turns into a race to stop an unbalanced ambulance EMT from imperiling the city's festivities. The misguided vigilante, playing cop with a stolen gun and uniform, has a bank vault full of reasons to put on his own fireworks show... one that will strike dangerously close to Knight's home.",
          popularity: 818.828,
          poster_path: "/jrPKVQGjc3YZXm07OYMriIB47HM.jpg",
          release_date: "2023-01-20",
          title: "Detective Knight: Independence",
          video: false,
          vote_average: 5.9,
          vote_count: 79,
        },
        {
          adult: false,
          backdrop_path: "/pxJbfnMIQQxCrdeLD0zQnWr6ouL.jpg",
          genre_ids: [28, 35, 53],
          id: 1077280,
          original_language: "en",
          original_title: "Die Hart",
          overview:
            "Follows a fictionalized version of Kevin Hart, as he tries to become an action movie star. He attends a school run by Ron Wilcox, where he attempts to learn the ropes on how to become one of the industry's most coveted action stars.",
          popularity: 1386.983,
          poster_path: "/1EnBjTJ5utgT1OXYBZ8YwByRCzP.jpg",
          release_date: "2023-02-22",
          title: "Die Hart",
          video: false,
          vote_average: 6.7,
          vote_count: 97,
        },
      ],
      total_pages: 7281,
      total_results: 145601
    },
  },
];
